/* ==========================================================================
   DONUT MARKET — shell.js
   Renders the navigation, the live market-status chip, the ticker tape and
   the footer on every page.

   The chrome is built here rather than copy-pasted into six HTML files so it
   can't drift between them, and so the session chip and account state are
   wired up exactly once.
   ========================================================================== */

const DM_SHELL = (() => {
  const NAV = [
    { href: 'index.html', label: 'Home', root: true },
    { href: 'market.html', label: 'Market' },
    { href: 'portfolio.html', label: 'Portfolio' },
    { href: 'leaderboard.html', label: 'Leaderboard' },
  ];

  let profile = null;
  let status = null;

  const url = (item) => (item.root ? DM.home() : DM.link(item.href));

  function currentPage() {
    const file = location.pathname.split('/').pop() || 'index.html';
    return file === '' ? 'index.html' : file;
  }

  function navMarkup() {
    const page = currentPage();
    const links = NAV.map(
      (item) => `<a href="${url(item)}"${item.href === page ? ' class="active" aria-current="page"' : ''}>${item.label}</a>`
    ).join('');

    return `
      <header class="navbar">
        <div class="container nav-inner">
          <a href="${DM.home()}" class="nav-logo"><span class="donut-mark">🍩</span> Donut Market</a>
          <nav class="nav-links" aria-label="Primary">${links}</nav>
          <div class="nav-actions">
            <span class="session-chip" id="session-chip" title="Exchange status">
              <span class="dot"></span><span class="txt">—</span>
            </span>
            <button class="theme-toggle" id="theme-toggle" type="button" aria-label="Switch theme" title="Switch theme">◑</button>
            <span id="account-slot" class="nav-account"></span>
          </div>
          <button class="nav-toggle" id="nav-toggle" type="button" aria-label="Toggle menu" aria-expanded="false">
            <span></span><span></span><span></span>
          </button>
        </div>
        <div class="mobile-menu card" id="mobile-menu">
          ${NAV.map((item) => `<a href="${url(item)}"${item.href === page ? ' class="active"' : ''}>${item.label}</a>`).join('')}
          <a href="${DM.link('login.html')}" id="mobile-account">Log in</a>
        </div>
      </header>
      <div class="tape" id="tape" hidden><div class="tape-track" id="tape-track"></div></div>
    `;
  }

  function footerMarkup() {
    return `
      <footer class="site-footer">
        <div class="container">
          <div class="footer-grid">
            <div class="footer-brand">
              <a href="${DM.home()}" class="nav-logo"><span class="donut-mark">🍩</span> Donut Market</a>
              <p>A simulated stock exchange. Real market microstructure, entirely fictional companies, zero real-world risk.</p>
            </div>
            <div class="footer-col">
              <h4>Trade</h4>
              <a href="${DM.link('market.html')}">Market</a>
              <a href="${DM.link('portfolio.html')}">Portfolio</a>
              <a href="${DM.link('leaderboard.html')}">Leaderboard</a>
            </div>
            <div class="footer-col">
              <h4>Exchange</h4>
              <a href="${DM.link('market.html')}#news">News wire</a>
              <a href="${DM.link('market.html')}#movers">Movers</a>
              <a href="/api/health">API status</a>
            </div>
            <div class="footer-col">
              <h4>Account</h4>
              <a href="${DM.link('login.html')}">Log in</a>
              <a href="${DM.link('admin.html')}">Admin console</a>
            </div>
          </div>
          <div class="footer-bottom">
            <span>© 2026 Donut Market</span>
            <span>Donut Coins have no real-world value. Prices are generated by a simulation — nothing here is financial advice.</span>
          </div>
        </div>
      </footer>
    `;
  }

  /* ------------------------------------------------------------- session UI */

  const SESSION_COPY = {
    pre: { cls: 'extended', txt: 'Pre-market' },
    regular: { cls: 'open', txt: 'Market open' },
    after: { cls: 'extended', txt: 'After hours' },
    closed: { cls: 'closed', txt: 'Closed' },
  };

  function renderSession() {
    const chip = DM.$('#session-chip');
    if (!chip || !status) return;
    const copy = SESSION_COPY[status.session] || SESSION_COPY.closed;
    chip.className = `session-chip ${copy.cls}`;

    let text = copy.txt;
    if (!status.is_open && status.next_open) {
      text += ` · opens ${countdown(status.next_open)}`;
    } else if (status.is_open && status.session_ends) {
      text += ` · ${countdown(status.session_ends)} left`;
    }
    DM.setText(chip.querySelector('.txt'), text);
    chip.title = `${copy.txt} — ${status.timezone}`;
  }

  function countdown(target) {
    const secs = Math.max(0, Math.round((target - Date.now()) / 1000));
    const d = Math.floor(secs / 86400);
    const h = Math.floor((secs % 86400) / 3600);
    const m = Math.floor((secs % 3600) / 60);
    if (d) return `in ${d}d ${h}h`;
    if (h) return `in ${h}h ${m}m`;
    return `in ${m}m`;
  }

  async function refreshStatus() {
    const { data } = await DM_API.marketStatus();
    if (data) {
      status = data;
      renderSession();
      document.dispatchEvent(new CustomEvent('dm:status', { detail: data }));
    }
  }

  /* ------------------------------------------------------------- account UI */

  function renderAccount() {
    const slot = DM.$('#account-slot');
    const mobile = DM.$('#mobile-account');
    if (!slot) return;

    if (!profile) {
      slot.innerHTML = `
        <a href="${DM.link('login.html')}" class="btn btn-ghost btn-sm">Log in</a>
        <a href="${DM.link('login.html')}?mode=signup" class="btn btn-primary btn-sm">Start trading</a>`;
      if (mobile) { mobile.textContent = 'Log in'; mobile.href = DM.link('login.html'); }
      return;
    }

    slot.innerHTML = `
      <a href="${DM.link('portfolio.html')}" class="balance-pill" title="Buying power — cash minus anything committed to resting orders">
        🍩 ${DM.coins(profile.buying_power)}<small>buying power</small>
      </a>
      ${profile.role === 'admin' ? `<a href="${DM.link('admin.html')}" class="btn btn-ghost btn-sm">Admin</a>` : ''}
      <button class="btn btn-quiet btn-sm" id="logout-btn" type="button">Log out</button>`;

    DM.$('#logout-btn').addEventListener('click', logout);
    if (mobile) {
      mobile.textContent = 'Log out';
      mobile.href = '#';
      mobile.onclick = (e) => { e.preventDefault(); logout(); };
    }
  }

  async function refreshProfile() {
    if (!DM_API.isLoggedIn()) {
      profile = null;
      renderAccount();
      return null;
    }
    const { data } = await DM_API.me();
    profile = data;
    renderAccount();
    document.dispatchEvent(new CustomEvent('dm:profile', { detail: profile }));
    return profile;
  }

  function logout() {
    DM_API.signOut();
    profile = null;
    window.location.href = DM.home();
  }

  /* ------------------------------------------------------------------- tape */

  async function renderTape() {
    const track = DM.$('#tape-track');
    if (!track) return;
    const { data } = await DM_API.quotes();
    if (!data || !data.quotes || !data.quotes.length) return;

    const items = data.quotes
      .map((q) => {
        const cls = DM.dirClass(q.change_pct);
        return `<a class="tape-item" href="${DM.link('company.html')}?t=${q.ticker}">
          <span class="sym">${DM.esc(q.ticker.toUpperCase())}</span>
          <span class="px">${DM.price(q.price)}</span>
          <span class="ch ${cls}">${DM.delta(q.change_pct)}</span>
        </a>`;
      })
      .join('');

    // Duplicated once so the marquee can loop seamlessly at -50%.
    track.innerHTML = items + items;
    DM.$('#tape').hidden = false;
  }

  /* ------------------------------------------------------------------- init */

  function mount() {
    const navSlot = DM.$('[data-shell="nav"]');
    if (navSlot) navSlot.outerHTML = navMarkup();
    const footSlot = DM.$('[data-shell="footer"]');
    if (footSlot) footSlot.outerHTML = footerMarkup();

    const toggle = DM.$('#nav-toggle');
    const menu = DM.$('#mobile-menu');
    if (toggle && menu) {
      toggle.addEventListener('click', () => {
        const open = toggle.classList.toggle('open');
        menu.classList.toggle('open', open);
        toggle.setAttribute('aria-expanded', String(open));
      });
    }

    const themeBtn = DM.$('#theme-toggle');
    if (themeBtn) themeBtn.addEventListener('click', DM.toggleTheme);

    document.addEventListener('dm:signed-out', () => { profile = null; renderAccount(); });
    // A fill changes buying power, so the navbar has to know about it.
    document.addEventListener('dm:trade', refreshProfile);

    refreshProfile();
    refreshStatus();
    if (DM.$('#tape')) renderTape();

    DM.poll(refreshStatus, 30000);
    DM.poll(renderTape, 15000);
    setInterval(renderSession, 30000);
    DM.initReveal();
  }

  return {
    mount,
    refreshProfile,
    refreshStatus,
    get profile() { return profile; },
    get status() { return status; },
  };
})();

window.DM_SHELL = DM_SHELL;
document.addEventListener('DOMContentLoaded', DM_SHELL.mount);
