const mongoose = require("mongoose");

// The news wire.
//
// Two kinds of story land here. Most are generated by the simulation itself:
// engine/price.js produces a jump, engine/news.js writes the headline that
// explains it, and services/market.js files it. The rest are published by an
// admin, which additionally kicks the price by the stated amount.
//
// Because engine-generated events are keyed by the tick that produced them,
// re-advancing the same stretch of time can never file the same story twice.
const marketEventSchema = new mongoose.Schema(
  {
    headline: { type: String, required: true },
    companyId: { type: String, default: null, index: true },
    companyName: { type: String, default: null },
    companyIcon: { type: String, default: null },
    impactPct: { type: Number, default: 0 },
    severity: { type: String, enum: ["minor", "moderate", "major"], default: "moderate" },
    source: { type: String, enum: ["market", "admin"], default: "market" },
    tick: { type: Number, default: null }, // engine tick that produced it
    at: { type: Date, default: Date.now, index: true },
  },
  { timestamps: true }
);

// Idempotency for engine-generated stories: one event per ticker per tick.
marketEventSchema.index({ companyId: 1, tick: 1 }, { unique: true, sparse: true });
marketEventSchema.index({ at: -1 });

marketEventSchema.set("toJSON", {
  transform: (_doc, ret) => {
    ret.id = String(ret._id);
    ret.company_id = ret.companyId;
    ret.impact_pct = ret.impactPct;
    delete ret._id;
    delete ret.__v;
    return ret;
  },
});

module.exports = mongoose.model("MarketEvent", marketEventSchema);
